POST http://127.0.0.1:8000/files/
Content-Type: application/json

{
  "file_name": "файл",
  "user_id": 5
}

###

GET http://127.0.0.1:8000/files/

###

GET http://127.0.0.1:8000/get_link_for_file/10/ 

###

DELETE http://127.0.0.1:8000/files/10/

###

GET http://127.0.0.1:8000/users/?password=123

###

POST http://127.0.0.1:8000/check_password/
Content-Type: application/json

{
  "login": "123",
  "password": "123"
}

###

POST http://127.0.0.1:8000/users/
Content-Type: application/json

{
  "name": "nikita",
  "login": "-nikita-",
  "password": "1234",
}