# Generated by Django 5.1.4 on 2025-03-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
